# Generated by Django 4.2.13 on 2024-10-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon name or identifier', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='minute',
            field=models.IntegerField(default=0, help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mode',
            field=models.IntegerField(default=1, help_text='Mode'),
        ),
        migrations.AlterField(
            model_name='device',
            name='pump_pin',
            field=models.CharField(default='V0', help_text='Pump PIN value from V0 to V50', max_length=3),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.IntegerField(choices=[(1, 'Relay'), (2, 'Sensor'), (3, 'Van')], default=1, help_text='Device type'),
        ),
    ]
