# Generated by Django 4.2.13 on 2024-11-02 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_device_icon_alter_device_minute_alter_device_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], help_text='Select day of the week for the timer')),
                ('start_time', models.TimeField(help_text='Start time for the device to turn on (HH:MM)')),
                ('end_time', models.TimeField(help_text='End time for the device to turn off (HH:MM)')),
                ('is_active', models.BooleanField(default=True, help_text='Status to activate or deactivate the timer')),
                ('device', models.ForeignKey(help_text='Linked device for the timer', on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='devices.device')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('device', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
