# Generated by Django 4.2.13 on 2024-11-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timer',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='timer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timer',
            name='days_of_week',
            field=models.JSONField(default=list, help_text='Select multiple days of the week for the timer'),
        ),
        migrations.RemoveField(
            model_name='timer',
            name='day_of_week',
        ),
    ]
