# Generated by Django 4.2.13 on 2024-11-03 18:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_key', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False, help_text='Current online status of the API')),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time the status was checked')),
                ('api_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='api_key.apikey')),
            ],
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(help_text="Event type, e.g., 'Connected', 'Disconnected', 'Restarted'", max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Time of the event')),
                ('description', models.TextField(blank=True, help_text='Additional details about the event')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api_key.apikey')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
